spring.application.name=jbooks

spring.datasource.url=jdbc:mysql://localhost:3306/books
spring.datasource.username=root
spring.datasource.password=Akhil#1486

#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properites.hibernate.format_sql=true

server.port=9000
spring.graphql.path=/graphql
spring.zipkin.enabled=false

spring.graphql.graphiql.enabled=true

management.tracing.enabled=false
